package forwardproxy

import (
	cryptotls "crypto/tls"
	"io"
	"net"
	"testing"
	"time"
)

// readAll drains a conn until EOF/close, returning what was read. Used to prove
// the sniffer replays the peeked bytes verbatim into the tunnel.
func readAll(t *testing.T, c net.Conn) []byte {
	t.Helper()
	_ = c.SetReadDeadline(time.Now().Add(2 * time.Second))
	b, _ := io.ReadAll(c)
	return b
}

// sniffServerSide accepts one connection on a fresh loopback listener, runs the
// client closure against its address, and returns sniffHost's result plus the
// bytes the wrapped conn yields (to verify replay).
func sniffServerSide(t *testing.T, client func(addr string)) (string, []byte) {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("listen: %v", err)
	}
	defer func() { _ = ln.Close() }()

	type result struct {
		host   string
		replay []byte
	}
	ch := make(chan result, 1)
	go func() {
		conn, err := ln.Accept()
		if err != nil {
			ch <- result{}
			return
		}
		host, wrapped := sniffHost(conn)
		ch <- result{host: host, replay: readAll(t, wrapped)}
	}()

	client(ln.Addr().String())

	select {
	case r := <-ch:
		return r.host, r.replay
	case <-time.After(5 * time.Second):
		t.Fatal("timed out waiting for sniff result")
		return "", nil
	}
}

// A real TLS ClientHello (generated by crypto/tls) with SNI must yield the SNI,
// and the handshake bytes must still be replayed for the tunnel.
func TestSniffHost_TLS_SNI(t *testing.T) {
	host, replay := sniffServerSide(t, func(addr string) {
		c, err := net.Dial("tcp", addr)
		if err != nil {
			t.Errorf("dial: %v", err)
			return
		}
		// Drive a real ClientHello with ServerName set. The handshake won't
		// complete (server side just sniffs and closes); we only need the
		// ClientHello on the wire.
		tlsConn := cryptotls.Client(c, &cryptotls.Config{
			ServerName:         "api.openai.com",
			InsecureSkipVerify: true, //nolint:gosec // test-only; no real verification
		})
		_ = tlsConn.SetDeadline(time.Now().Add(1 * time.Second))
		_ = tlsConn.Handshake() // expected to fail; ClientHello is what matters
		_ = c.Close()
	})

	if host != "api.openai.com" {
		t.Errorf("SNI host = %q, want api.openai.com", host)
	}
	if len(replay) == 0 || replay[0] != 0x16 {
		t.Errorf("replay did not start with a TLS record (0x16); got %d bytes", len(replay))
	}
}

// A plaintext HTTP request must yield the Host header, port stripped, and the
// full request must be replayed.
func TestSniffHost_HTTP_Host(t *testing.T) {
	req := "GET /v1/models HTTP/1.1\r\nHost: api.example.org:8080\r\nUser-Agent: x\r\n\r\n"
	host, replay := sniffServerSide(t, func(addr string) {
		c, err := net.Dial("tcp", addr)
		if err != nil {
			t.Errorf("dial: %v", err)
			return
		}
		_, _ = c.Write([]byte(req))
		_ = c.Close()
	})

	if host != "api.example.org" {
		t.Errorf("HTTP host = %q, want api.example.org (port stripped)", host)
	}
	if string(replay) != req {
		t.Errorf("replay = %q, want the original request verbatim", replay)
	}
}

// Non-HTTP, non-TLS bytes yield no hostname but are still replayed verbatim.
func TestSniffHost_Opaque(t *testing.T) {
	payload := []byte{0x00, 0x01, 0x02, 0x03, 0xff}
	host, replay := sniffServerSide(t, func(addr string) {
		c, err := net.Dial("tcp", addr)
		if err != nil {
			t.Errorf("dial: %v", err)
			return
		}
		_, _ = c.Write(payload)
		_ = c.Close()
	})

	if host != "" {
		t.Errorf("opaque host = %q, want empty", host)
	}
	if string(replay) != string(payload) {
		t.Errorf("replay = %v, want %v", replay, payload)
	}
}

func TestShouldSniff(t *testing.T) {
	cases := map[string]bool{
		"1.2.3.4:443":  true,
		"1.2.3.4:80":   true,
		"1.2.3.4:8443": true,
		"1.2.3.4:22":   false,
		"1.2.3.4:5432": false,
		"[::1]:443":    true,
		"garbage":      false,
	}
	for in, want := range cases {
		if got := shouldSniff(in); got != want {
			t.Errorf("shouldSniff(%q) = %v, want %v", in, got, want)
		}
	}
}
